foreground #ffffff
background #240037
selection_foreground #240037
selection_background #ffffff

cursor #ff00ff
cursor_text_color #240037

active_border_color #0080ff
active_tab_background #0080ff

color0 #262335
color1 #ff0040
color2 #8f00ff
color3 #f3e70f
color4 #0080ff
color5 #ff00ff
color6 #03edf9
color7 #ffffff
color8 #614d85
color9 #fe5442
color10 #fe5442
color11 #ffff66
color12 #0080ff
color13 #ff7edb
color14 #03edf9
color15 #ffffff
