# ────────────────────────────────────────────────────────────
#  Hyprlock — Synthwave '84 theme
# ────────────────────────────────────────────────────────────

$color = rgba(26,5,26,1.0)  # #1A051A solid color

$inner_color = rgba(26,5,26,0.8)  # #1A051A with opacity
$outer_color = rgba(143,0,255,1.0)  # #8f00ff

$font_color = rgba(143,0,255,1.0)
$placeholder_color = rgba(255,255,255,0.7)
$check_color = rgba(223, 0, 255, 1.0)
